### ISSUE TITLE
Stopped working today

### ISSUE THREAD

**Issue by MattVipond** [StephenBlackWasAlreadyTaken/NightWatch#132]
Stopped working today - no data.  Checked with other users,  same problem.  Please continue to support this app, it is a life saver!!!

**Comment by T1DDad2010** [comment]
Agreed. This app is way better than the Dexcom follow app. Mine stopped working at around 1615 central time

**Comment by Rocket-Fueled** [comment]
Nightwatch stopped working for me as well.  It loads, displays a graph of the data it has, and shares with WearableWidgets, but it stopped reading data from Dexcom Share around 2:15PM PDT.

**Comment by justritedesign** [comment]
Mine stopped at around 3:40 PM CST
Hope they can fix this as I just love this app.

**Comment by ehox5** [comment]
Mine stopped working yesterday too. I can't find a way for it to update with dexcom numbers.

**Comment by aaykayg** [comment]
Same experience here. Any idea what has changed?

**Comment by WildcatOne** [comment]
Mine stopped working around 4:30 EST on yesterday.

**Comment by thanksegon** [comment]
Xdrip has a follow mode, I believe.


Joe Ritson
Cell Phone: 617.775.7750
LinkedIn: www.linkedin.com/in/josephritson<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fjosephritson&data=02%7C01%7C%7C0850151ed34b4c77494208d80eecebec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637275758010462860&sdata=rf7LUtVoHgFV5vy8NVGLMGXbHR1hVPHwXduJBPXliQY%3D&reserved=0>

________________________________
From: MattVipond ***@***.***>
Sent: Wednesday, June 23, 2021 1:58 AM
To: StephenBlackWasAlreadyTaken/NightWatch
Cc: Subscribed
Subject: [StephenBlackWasAlreadyTaken/NightWatch] Stopped working today (#132)


Stopped working today - no data. Checked with other users, same problem. Please continue to support this app, it is a life saver!!!

**Comment by suckafreem3** [comment]
Same thing for me, It stopped pulling data sometime last night at around 2am or so I think.  Does anyone know what has changed or if anything is going on?

**Comment by MattVipond** [comment]
It must have to do with the dexcom interface,  because i switched over to pull data from my nightscout site, and that works.   Weird because nightscout just pulls from dexcom too...  but it might be an option for you to get NightWatch back working for you!

**Comment by suckafreem3** [comment]
I guess I will set that up, I never set up the Nightscout site because I'm not super confident in my understanding of repositories, and whatnot.  Why not be forced to learn it i guess lol

**Comment by nneuhardt** [comment]
Please please support this app!! Its a lifesaver for those who still use Dexcom app for glucose values to Samsung Tizen! Stopped receiving values roughly 48 hours ago.

**Comment by nneuhardt** [comment]
> Please please support this app!! Its a lifesaver for those who still use Dexcom app for glucose values to Samsung Tizen! Stopped receiving values roughly 48 hours ago.

No clue, what just happened, but I started receiving values again. Something/someone update?

**Comment by Seismal** [comment]
Working for me now too.  This issue can be closed, I believe.

**Comment by suckafreem3** [comment]
Is anyone aware of what caused the issue?  It's just very strange, and a little worrisome, that for 12 hours or so there was an outage.

**Comment by T1DDad2010** [comment]
Looks like it is working again for me

**Comment by ehox5** [comment]
it is working again for me too

**Comment by Rocket-Fueled** [comment]
It has started working again for me as well.  What a relief!

**Comment by suckafreem3** [comment]
So 41 minutes ago Nightwatch stopped working for me again.  Nightscout is still updating and working for me

**Comment by thanksegon** [comment]
Can someone help me for a moment. If xdrip can follow NS, why is nightwatch so important? What does NW do that xdrip doesn't?

Joe Ritson
Cell Phone: 617.775.7750
LinkedIn: www.linkedin.com/in/josephritson<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fjosephritson&data=02%7C01%7C%7C0850151ed34b4c77494208d80eecebec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637275758010462860&sdata=rf7LUtVoHgFV5vy8NVGLMGXbHR1hVPHwXduJBPXliQY%3D&reserved=0>

________________________________

**Comment by nneuhardt** [comment]
> Can someone help me for a moment. If xdrip can follow NS, why is nightwatch so important? What does NW do that xdrip doesn't? Joe Ritson Cell Phone: 617.775.7750 LinkedIn: [www.linkedin.com/in/josephritson<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fjosephritson&data=02%7C01%7C%7C0850151ed34b4c77494208d80eecebec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637275758010462860&sdata=rf7LUtVoHgFV5vy8NVGLMGXbHR1hVPHwXduJBPXliQY%3D&reserved=0](http://www.linkedin.com/in/josephritson<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fjosephritson&data=02%7C01%7C%7C0850151ed34b4c77494208d80eecebec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637275758010462860&sdata=rf7LUtVoHgFV5vy8NVGLMGXbHR1hVPHwXduJBPXliQY%3D&reserved=0)>
> […](#)
> ________________________________ From: suckafreem3 ***@***.***> Sent: Wednesday, June 23, 2021 1:58 PM To: StephenBlackWasAlreadyTaken/NightWatch Cc: thanksegon; Comment Subject: Re: [StephenBlackWasAlreadyTaken/NightWatch] Stopped working today (#132) So 41 minutes ago Nightwatch stopped working for me again. Nightscout is still updating and working for me — You are receiving this because you commented. Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FStephenBlackWasAlreadyTaken%2FNightWatch%2Fissues%2F132%23issuecomment-867044834&data=04%7C01%7C%7C798a2ae557ed4c565afa08d936708fde%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637600679333987742%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=aasvzLt%2BldepBf%2BuezzF4TOOM9fTDku13zHmEAN1KZY%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFLE7YADZ7MA6RJJZGSSHVTTUIOFZANCNFSM47FCHOYQ&data=04%7C01%7C%7C798a2ae557ed4c565afa08d936708fde%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637600679333997731%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=bGo66HY3CFCb%2FG5jIlZ3dxZdATGmRSH0EkdrXMCvaY4%3D&reserved=0>.

In short, I enjoy using the dexcom app for glucose readings, nightwatch allows me to continue to use the dexcom app as well as display my values on my tizen watch.

**Comment by thanksegon** [comment]
My husband has xdrip on his phone, following my NS, and he displays my numbers on his Wear OS watch. Does xdrip not connect to the tizen?


Joe Ritson
Cell Phone: 617.775.7750
LinkedIn: www.linkedin.com/in/josephritson<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fjosephritson&data=02%7C01%7C%7C0850151ed34b4c77494208d80eecebec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637275758010462860&sdata=rf7LUtVoHgFV5vy8NVGLMGXbHR1hVPHwXduJBPXliQY%3D&reserved=0>


________________________________

**Comment by MattVipond** [comment]
I am a parent of a T1d little.  The alarms on Dexcom follow suck.  I use NightWatch on my phone to "follow" his numbers across the house.  NightWatch will wake me up and alert me to a high or a low.

That is how I use NightWatch.  Now, back at you, why would I need xdrip?

**Comment by thanksegon** [comment]
NW seems to be abandoned. If that's not a problem for you (no sarcasm) then stay with NW. It's too much risk for me, though, so we setup xdrip to Follow and it does everything NW does.

Joe Ritson
Cell Phone: 617.775.7750
LinkedIn: www.linkedin.com/in/josephritson<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fjosephritson&data=02%7C01%7C%7C0850151ed34b4c77494208d80eecebec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637275758010462860&sdata=rf7LUtVoHgFV5vy8NVGLMGXbHR1hVPHwXduJBPXliQY%3D&reserved=0>


________________________________

**Comment by MattVipond** [comment]
I agree, NightWatch does seem abandoned, and I'm not OK with it.  But I dont see how xDrip does what i want.  I need an app setup on my phone, not my T1Ds phone.  xDrip looks like it gets setup on his phone to upload to my Nightscout site, am I missing something?

**Comment by thanksegon** [comment]
I'm not sure I understand your desired setup. But, if your T1D is using xdrip on his phone to upload to Nightscout, you can use xdrip on your phone to follow, just like you used Nightwatch to follow. If I misunderstand your desired setup, correct me and I'll do my best to help.

Joe Ritson
Cell Phone: 617.775.7750
LinkedIn: www.linkedin.com/in/josephritson<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fjosephritson&data=02%7C01%7C%7C0850151ed34b4c77494208d80eecebec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637275758010462860&sdata=rf7LUtVoHgFV5vy8NVGLMGXbHR1hVPHwXduJBPXliQY%3D&reserved=0>


________________________________

**Comment by MattVipond** [comment]
Thank you!  Investigating xdrip on my phone now.  My T1D just runs Dexcom app on his phone, but I may be open to changing that if there is some value in it.   Currently my Nightscout site jist gets its data through the dexcom follow site.  I was thinking I could just run xdrip on his phone, but to date have not seen an advantage.  But perhaps xDrip has the biggest advantage of being currently supported. . .

**Comment by thanksegon** [comment]
Is he the only T1D or are you, as well?

To simplify, he could upload his cgm data directly (xdrip on his phone to NS) and discontinue  Dexcom follow site, unless it's needed for something else. Then, you would install xdrip on your phone, choose Follow as your Source, enter the T1D's Nightscout info and then you're following his numbers.

I hope this addresses your needs.

Joe Ritson
Cell Phone: 617.775.7750
LinkedIn: www.linkedin.com/in/josephritson<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fjosephritson&data=02%7C01%7C%7C0850151ed34b4c77494208d80eecebec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637275758010462860&sdata=rf7LUtVoHgFV5vy8NVGLMGXbHR1hVPHwXduJBPXliQY%3D&reserved=0>


________________________________

**Comment by nneuhardt** [comment]
@thanksegon I've had xdrip+ before, I know I'm probably the minority, but was not a big fan. I used it for about 1yr and finally reverted back to dexcom after having to "fiddle" with the updates constantly. Dexcom is seamless when it comes to updates. Don't get me wrong, xdrip+ had great advantages and I appreciate the efforts and coding that has gone into the product, I just enjoy the dexcom app at this moment in my T1D journey.

The nice thing about nightwatch is it allows me to keep the dexcom app and display those values on my tizen watch (which is very valuable), without xdrip being setup and configured. 

Nightwatch, to me, is seriously a lifeline that I use multiple times throughout the day, in conjunction with the dexcom app. 

It would be great to see this application not abandoned :-)

**Comment by thanksegon** [comment]
Xdrip is certainly more complex than nightwatch. If it's a shame that it's been abandoned.

Joe Ritson
Cell Phone: 617.775.7750
LinkedIn: www.linkedin.com/in/josephritson<https://nam05.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.linkedin.com%2Fin%2Fjosephritson&data=02%7C01%7C%7C0850151ed34b4c77494208d80eecebec%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637275758010462860&sdata=rf7LUtVoHgFV5vy8NVGLMGXbHR1hVPHwXduJBPXliQY%3D&reserved=0>

________________________________

**Comment by MattVipond** [comment]
Nightwatch working now.  Unknown problem, but seems to have corrected itself . . .
