### ISSUE TITLE
Graph formatting of square watch face get a bit screwy

### ISSUE THREAD

**Issue by xitation** [StephenBlackWasAlreadyTaken/NightWatch#14]
Graph formatting seems to get a bit screwy, restart of watch appears to fix it. 

![screen](https://cloud.githubusercontent.com/assets/1818975/6745634/eb2c42ba-cf0d-11e4-94aa-92a80b3736d9.png)

**Comment by xitation** [comment]
Don't mind the gaps in the data there, that was some bridge issues.

**Comment by StephenBlackWasAlreadyTaken** [comment]
https://github.com/StephenBlackWasAlreadyTaken/NightWatch/commit/d080f7d86badb0d3abe43543aaaba5be696df375 resolved
