### ISSUE TITLE
Battery level reported with share2+xDrip isn't valid

### ISSUE THREAD

**Issue by saercnap** [StephenBlackWasAlreadyTaken/NightWatch#15]
I've got a share2 connected to xDrip, and nightwatch is reporting a 36% battery level. The share2 is fully charged are the phone and watch.

Is this filler data?

**Comment by StephenBlackWasAlreadyTaken** [comment]
resolved https://github.com/StephenBlackWasAlreadyTaken/NightWatch/pull/17/files
