### ISSUE TITLE
Endpoint follows DISPLAY_UNITS=mmol setting. Nightwatch crashes.

### ISSUE THREAD

**Issue by StuArnold** [StephenBlackWasAlreadyTaken/NightWatch#16]
Previously endpoint was always in mg and users had to append ?units=mmol to the endpoint in the pebble to get display in mmol. Using Enchilada (0.7 Dev) the end point follows the DISPLAY_UNITS setting so if set to mmol it gives a mmol value e.g. 6.4 in the SGV value of the endpoint. Nightwatch then crashes and data has to be cleared before it will restart. Work around is to append /pebble?units=mg to the end point in Nightwatch to force it to take the mg value. Could this be added to the code so that instead of appending "/pebble" to the entered endpoint it appends "/pebble?units=mg". I would assume that this would then work for everyone.

**Comment by StephenBlackWasAlreadyTaken** [comment]
Definitely!! Thanks for the heads up!

**Comment by StephenBlackWasAlreadyTaken** [comment]
resolved https://github.com/StephenBlackWasAlreadyTaken/NightWatch/pull/17/files

**Comment by StuArnold** [comment]
Thank you. See lots of changes. Is there more to come or should I be
heading to Android Studio. Currently running Beta 0.9.01 that you linked to
in a post. Thanks again
