### ISSUE TITLE
Data Backfill/Gap Sync Feature Request

### ISSUE THREAD

**Issue by aaronjknox** [StephenBlackWasAlreadyTaken/NightWatch#2]
Stephen & other Nightwatch dev's.  Please take a look at this issue for improved viewing of older data.

Issue:
-gaps in the Nightwatch trendline can be seen when compared to Nightscout web-viewer(see below 1-2 a.m.)
Request:
-a function that serves to ensure and/or force syncing of the missed data. Serving a similar purpose as the Gap Sync function in https://github.com/nightscout/android-uploader/
**Thanks!!**

**Nightwatch:**

![nw gap 1-12](https://cloud.githubusercontent.com/assets/7867106/5712346/bbba432a-9a6e-11e4-81ea-2992e0abc446.png)

**Nightscout:**

![hero1_12](https://cloud.githubusercontent.com/assets/7867106/5712349/c1c08d38-9a6e-11e4-874b-ac927eecceb5.jpg)

**Comment by StephenBlackWasAlreadyTaken** [comment]
resolved https://github.com/StephenBlackWasAlreadyTaken/NightWatch/pull/17

**Comment by jbriley** [comment]
Stephen, I see that you have resolved the issue of gap syncing when using a nightscout site. Is this not working when using the Dexcom Share servers as the data source?
