### ISSUE TITLE
Nightwatch: No data displayed after initial install + sign in (Dexcom option)

### ISSUE THREAD

**Issue by YYCMichael** [StephenBlackWasAlreadyTaken/NightWatch#23]
Hi,

After installing Nightwatch on my Android phone and selecting the Dexcom share option I am prompted for a user name and password. I enter my details as I would from Dexcom but there is no status window to determine if the connection was successful; the end result is that there is no data displayed in the main interface. Is there a set-up readme file I need to review?

**Comment by StephenBlackWasAlreadyTaken** [comment]
unfortunately no readme with instructions, but you have an iphone currently uploading to dexcoms servers and can also follow on that same iPhone?

**Comment by YYCMichael** [comment]
Hiyo!

Friend has the iphone uploading to dexcom yep. I can follow via the Follow App on my iPod (4th gen); can't do so on the droid (Nexus 6, 
![screenshot_2015-05-14-12-23-57](https://cloud.githubusercontent.com/assets/417795/7638791/7c183dc8-fa34-11e4-9333-341745b7e4f4.png)
![screenshot_2015-05-14-12-23-48](https://cloud.githubusercontent.com/assets/417795/7638792/7c30d72a-fa34-11e4-9073-ad0ae46caf29.png)

**Comment by LuminaryXion** [comment]
Hi Stephen! It's me! (same on twitter ^_^)

I don't have the follow app on my sharing iphone, because I am using BT Share2, so it shows my numbers to me without needing the follow app. Is that a problem?

Thanks bunches!

**Comment by shaylonnightscout** [comment]
Same here. I can follow on an iPhone but not my Samsung phone. Any ideas?

**Comment by StephenBlackWasAlreadyTaken** [comment]
try either restarting the phone or force closing the app and then opening it up again, it seems on some phones it dosnt recognize that the settings have changed and therefore dosnt start looking for new data right away.
@LuminaryXion you will need to invite yourself as a follower (even if you just put them both on the same phone, which seems silly but after that you can uninstall the follow app)

**Comment by shaylonnightscout** [comment]
That did it.  Thank you soooo much!

**Comment by StephenBlackWasAlreadyTaken** [comment]
This is addressed in the codebase and will be fine in all future versions, closing the issue!
