### ISSUE TITLE
feature suggestion/question

### ISSUE THREAD

**Issue by ruiannie** [StephenBlackWasAlreadyTaken/NightWatch#24]
is there a way to make it so when we click on the widget it will load the application and we can see the graph without having to make a shortcut next to the widget to view the graph?

Thank you for all your hard work. This application has truly changed my life.

**Comment by StephenBlackWasAlreadyTaken** [comment]
Will definitely add this!

**Comment by StephenBlackWasAlreadyTaken** [comment]
added! all future versions will have this!
