### ISSUE TITLE
Watch faces are unavailable after watch update to 5.1.1

### ISSUE THREAD

**Issue by aaronjknox** [StephenBlackWasAlreadyTaken/NightWatch#25]
The Android Wear watch OS update to 5.1.1 makes choosing a Nightwatch face impossible via phone or watch. Alert notifications still work.

**Comment by aaronjknox** [comment]
This is occurring on the LG G Watch.

**Comment by StephenBlackWasAlreadyTaken** [comment]
@mgranberry has a solution, will keep you posted

**Comment by Docdavesi** [comment]
I have 2 LG G watches which have lost their nightwatch faces spontaneously.  2 different phone both using KitKat: Note 3 using 4.4.2 and S3 using 4.2
I've tried reloading nightwatch and factory resetting the watches.  Still am not able to see the nightwatch faces.  I think Android wear app was updated.
This did not effect a Note 3 running 5.0 with Sony watch 3

**Comment by aaronjknox** [comment]
Thanks!

**Comment by Docdavesi** [comment]
Worked!  Thanks


Sent from my T-Mobile 4G LTE Device

-------- Original message --------
