### ISSUE TITLE
Missing Change value with nightwatch 1.0.2

### ISSUE THREAD

**Issue by speed2O** [StephenBlackWasAlreadyTaken/NightWatch#30]
With first nightwatch there was a +/- ml/d value on the watch face alongside the BG readout(under the arrow(s)). But now that is missing with new update. Thank you for the update, andkeep up the great work. It has been truly life changing!

**Comment by StephenBlackWasAlreadyTaken** [comment]
Thats odd, it should still be there, it was never removed from the layout.

Mind posting a pic of what you are seeing?
Also, where do you have NightWatch pulling values from (from nightscout, from Dexcom servers, or from xDrip?)

**Comment by AdrianLxM** [comment]
I'm having the same issue:
![No delta on watch](http://up.picr.de/22096531bj.jpg)

**Comment by AdrianLxM** [comment]
I'm using the wixel-solution.

BTW: the "large"-Watchface still has the delta.

**Comment by StephenBlackWasAlreadyTaken** [comment]
Thanks for the pic!, speed, are you also using a square watch? If so it
must be square template related. I'll check it out tonight!

**Comment by AdrianLxM** [comment]
What fixed it for me is deleting 

android:singleLine="true" 

in rec_activity_home.xml

**Comment by AdrianLxM** [comment]
![Delta again :) ](http://up.picr.de/22098421rq.jpg)

**Comment by AdrianLxM** [comment]
Also tested on my friend's Sony Smart Watch 3:
![Delta again :) ](http://up.picr.de/22101696fa.jpg)

Both have latest updates.

**Comment by xitation** [comment]
I've just compiled and tested patch on Google LG Watch, seems to work well.

Thanks.

**Comment by speed2O** [comment]
Yes I have the g watch thank you everyone for the pics I was trying to do watch screenshots but it always failed * not related to nightwatch*  and I use dark with graph watchface.

**Comment by speed2O** [comment]
Thank you AdrianLxM that info will be really helpful I will dive into removing that line later today.

**Comment by AdrianLxM** [comment]
When the line is too long for the TextView including margin, ... , it will just hide the whole line on Android Wear if "singleLine" is set to true, it seems. Others made the same experience.

Maybe it would help to set horizontasSrolling? I'm not sure if this would work on wear? It should be the standard behaviour for single lines: http://developer.android.com/reference/android/widget/TextView.html#attr_android:singleLine

If "ellipisize" (http://developer.android.com/reference/android/widget/TextView.html#attr_android:ellipsize) is enabled, it should show but with dots.

What I don't understand is why this happens here, as the width is set to "wrap_content" and the line isn't actually too large. Just deleting the line seems to work just fine.

Another "strange" thing: The "singleLine" attribute had been "deprecated" before but now it no longer is.

**Comment by speed2O** [comment]
Thank you AdrianLxM, xitation, and of course StephenBlackWasAlreadyTaken this issue has been resolved. I hope this project continues.  In my opinion this is the single best part about owning android wear!
