### ISSUE TITLE
Watch faces disappeared 

### ISSUE THREAD

**Issue by eneficus** [StephenBlackWasAlreadyTaken/NightWatch#40]
Watch faces disappeared from my watch face selection. I have uninstalled and reinstalled and the faces are not coming back. Is there a way to force add the faces or a fix for this?

**Comment by Vaughanabe13** [comment]
If you are using the latest version they changed it so all the watchfaces are combined in one, and you open the settings in android wear in order to change large/small and dark/light options among other things.
