### ISSUE TITLE
Bring over xDrip beta updates

### ISSUE THREAD

**Issue by whoiswes** [StephenBlackWasAlreadyTaken/NightWatch#41]
As a parent of a 3 year old Type 1, we leverage xDrip on an uploader phone to get our son's CGM data to NightScout, but we are running NightWatch on several different phones/tablets (with smartwatches coming soon).  One of the things that's preventing us from leaving his receiver downstairs is the fact that Nightwatch doesn't have any way to alert on missed readings.

I've just updated the uploader to the xDrip 2 beta, and it's nearly perfect in terms of configuration options - would it be possible to either:

1.  Port over the xDrip alert code to Nightwatch, to give the same customization options as xDrip has 

or 

2.  Update xDrip to allow for a "monitor-only" mode (ie, not an uploader, just a reader).  I realize this isn't the xDrip issues list but figured it was worth mentioning here.

Not sure on the architectural direction that these two projects are going, so feel free to close or redirect this as needed.

Many thanks for everyone's work on these projects, they are (literally) lifesavers!

**Comment by StephenBlackWasAlreadyTaken** [comment]
Yup! Porting the alerts and such over is part of the gameplan! Might be a bit tricky as we wound up building it up more than we originally expected to! One day we will get the two projects back in sync!

**Comment by christerjensen** [comment]
As a father of a 5 year old Type 1 I also found the new features in xdrip exerimental your released today what we have been missing in Nightwatch. I would love these xdrip features in Nightwatch! It would mean a lot to us that monitor children.

**Comment by oglematt** [comment]
I'm loving the new updates to xDrip and would like to add my "me too" to this issue.

**Comment by StephenBlackWasAlreadyTaken** [comment]
Just want to note that work on moving the alerts over has started, hopfully I will have it done soon!

**Comment by whoiswes** [comment]
I think this one can be closed out!
