### ISSUE TITLE
Graph not updating in version 1.0.2

### ISSUE THREAD

**Issue by christerjensen** [StephenBlackWasAlreadyTaken/NightWatch#42]
The graph is not updating in version 1.0.2. Use Huawei P7. The app opens, shows the graph, but it is not updating during the night. The graph is updated every time I close the app and opens it again. 

It seems like the phone is very slow when the app is running.

Had to go bak to v 0.9

**Comment by christerjensen** [comment]
Built a new apk from AdrianLxMs branch to test. The widget works fine, and the graph updates during the night in the widget (but still not the graph in Nightwatch, AdrianLxM hasn't changed anything he reports). 

Since I'm a parent I only have Nightwatch on my phone, hence Nightwatch collects data from internett. 

I now use Nightwatch in the background for alarms during night, and a webbrowser to show the graph since it is updated there.

**Comment by AdrianLxM** [comment]
I think I found the bug during lunch break. I might have a patch out tonight.

**Comment by AdrianLxM** [comment]
I added the fix to my branch https://github.com/AdrianLxM/NightWatch/tree/circleWatchfaceSettings02, if you'd like to test it @christerjensen.

If you'd like to stay with current master, it is this pull request: https://github.com/StephenBlackWasAlreadyTaken/NightWatch/pull/47
