### ISSUE TITLE
Custom Android Notifications Do Not Work As Alert Sound

### ISSUE THREAD

**Issue by xrimson** [StephenBlackWasAlreadyTaken/NightWatch#49]
I have added custom android notifications and can see them under NightWatch settings -> BG Level Alerts -> Alert Sound.  However when I select them, I do not hear them.  If I change to a default notification sound it works.  Just nothing custom that I added.  I added different formats (mp3, wav) to the Home/Notifications folder.  I also tried an app that can edit ringtones and save them as notifications.  These all showed in settings, but I never actually heard any sound (even waiting longer than the snooze setting).

User Story - I am a T1D parent.  I am trying to get a longer alert, so it will wake me up at night.  I have done 1 minute snooze, but it is still not enough.  I was hoping to add a custom sound to android notifications that is longer (20-30 seconds) that could pull me from deep sleep.  I know there are other options such as turning the sound up really loud... but I don't want to have to turn that up every night and down every morning.

**Comment by StephenBlackWasAlreadyTaken** [comment]
The changes you need are in this pr already
https://github.com/StephenBlackWasAlreadyTaken/NightWatch/pull/48 which
will hopefully be moving into master soon. I just have a bit more work to
do. Feel free to compile and use this branch, it's quite stable
