### ISSUE TITLE
Out of range displays as LOW

### ISSUE THREAD

**Issue by corylink** [StephenBlackWasAlreadyTaken/NightWatch#5]
Dex receiver showed out of range, but Nightwatch reported as LOW.

![nw](https://cloud.githubusercontent.com/assets/8398032/5879343/a666056a-a2eb-11e4-8a88-e5ff3ced759b.png)

**Comment by StephenBlackWasAlreadyTaken** [comment]
I will look in to this, I suppose nightscout still sends up a value even if readings were missed

**Comment by StephenBlackWasAlreadyTaken** [comment]
should be addressed here: https://github.com/StephenBlackWasAlreadyTaken/NightWatch/pull/11

**Comment by StephenBlackWasAlreadyTaken** [comment]
resolved
