### ISSUE TITLE
Alarms will keep alerting when last reading was high/low

### ISSUE THREAD

**Issue by corylink** [StephenBlackWasAlreadyTaken/NightWatch#6]
So, I am not sure there is a solution to this, but thought I would get you thinking.  We are using Dex for our 3 year old.  Meaning we mainly use it when he is sleeping, as he is almost always with us.  So, we connect for bedtime and nap and disconnect for the rest of the day.  Well, if we disconnect when Nightwatch is in an alert state, I will continue to get the alerts all day long until the next time we connect.  I realize that I can shut the alert off in settings, but I would rather not shut off alerts for fear of not remembering to turn them back on.  Any thoughts?

**Comment by StephenBlackWasAlreadyTaken** [comment]
Hmmmm, I definitely can see how that would be an issue
at the same time, Its probably safer to alarm than to just assume the connection was lost but they probably got back to good bg levels...

Not sure I have a good solution to this.

**Comment by corylink** [comment]
Just thought of a possibility... perhaps we suggest to Nightscout developers to have a different value/display when there is no USB connection between uploader and dex.  Even something like "USB".  Then you can trigger on that and have it display the same USB and not alert on that condition???

**Comment by StephenBlackWasAlreadyTaken** [comment]
also in https://github.com/StephenBlackWasAlreadyTaken/NightWatch/pull/11 I added that it should not alert for a reading if that reading is more than an hour old

**Comment by StephenBlackWasAlreadyTaken** [comment]
resolved
