### ISSUE TITLE
Late update problem

### ISSUE THREAD

**Issue by francesc0-cgm** [StephenBlackWasAlreadyTaken/NightWatch#60]
Nightwatch receives updated BG on time but the watchface updates after 1-2 minutes when the phone is sleeping. When screen is on, on the phone, updated BG comes instantaeously

**Comment by AdrianLxM** [comment]
I can confirm this.
https://github.com/StephenBlackWasAlreadyTaken/NightWatch/pull/62 seems to solve it.

**Comment by AdrianLxM** [comment]
... it seemed to solve it on my phone, but not on Alessandro's.
It could be that the DataLayerThread is not "wakelocked" properly.

**Comment by francesc0-cgm** [comment]
Last commit is a great improvement. Solid updates at 6' at least early 7', very similar to pebble

**Comment by francesc0-cgm** [comment]
However the problem still remains. If you keep the screen on the phone on, BG value arrives immediately when NS is updated

**Comment by AdrianLxM** [comment]
... in the REST-code there is also a wakelock that isn't called "acquire()" on.

**Comment by francesc0-cgm** [comment]
It was a problem of miui7 of my phone. Now with a cm12 i have no problem at all. It comes a bit later as on pebble due to xdrip with share lag
