### ISSUE TITLE
Feature Request: Ability to snooze alerts from Watch.

### ISSUE THREAD

**Issue by xitation** [StephenBlackWasAlreadyTaken/NightWatch#67]
Hi All,

I think it would be nice to be able to snooze alarms generated from NightWatch OR xDrip* when they are shown on the Ware watch face.

Would love it if someone added this eventually. 

Thanks.

**Comment by AdrianLxM** [comment]
Works perfectly on my watch since at least 6 month.
I just set a default snooze time in the alert settings and on swipe to the right it will get snoozed.

**Comment by AdrianLxM** [comment]
I'll close this issue then.
