### ISSUE TITLE
NightWatch Delta values have incorrect sign.

### ISSUE THREAD

**Issue by Hebes24** [StephenBlackWasAlreadyTaken/NightWatch#73]
Having a weird glitch where in the NightWatch app, the delta values that are displayed have the wrong sign on them (i.e. +4 when it should be -4). xDrip delta values are correct, but deltas from NightWatch, when displayed on my ASUS Zenwatch 2 have this issue.

My phone is a Samsung Galaxy S6 that is running xDrip and NightWatch using Dexcom Share with a Dexcom G4. I am using Dexom Share servers for upload from xDrip and download to NightWatch.

**Comment by AdrianLxM** [comment]
Does this happen with every delta? Does it always show exactly the negated sign or does it show another delta value as well?
What version of xDrip and what version of NightWatch are you using?

**Comment by Hebes24** [comment]
Correct Value, incorrect sign (literally a '+' when there should be a '-', and vice versa). Also, the arrow is in the correct direction and the graph displays correctly. 

Using xDrip 2.0.3a and NightWatch 2.0.3.

**Comment by AdrianLxM** [comment]
Do you have NightScout and xDrip on the same phone? In this case you could check if the delta is correct with local broadcasts instead of going via the share server.

**Comment by AdrianLxM** [comment]
I think I found the bug. Thanks for reporting! I will try to fix it until monday.
@Hebes24, would you like to test it (I have no Share)? If yes, do you self-compile or do you need an .apk?

Note for fixing this: https://github.com/StephenBlackWasAlreadyTaken/NightWatch/blob/master/mobile/src/main/java/com/dexdrip/stephenblack/nightwatch/sharemodels/ShareGlucose.java#L102:
`bg.sgv_double() - currentValue` should be: `currentValue - bg.sgv_double()`.

**Comment by Hebes24** [comment]
I'd be happy to test it. I would need an .apk for that.

How do you setup the local broadcast? I see the option for it in xDrip to turn it on, but I was unsure of how to configure NightWatch to work with it. If it's simple enough I'd probably end up using that, since it sounds like I'd be able to cut out the Share servers, which would streamline my process (effectively eliminating the middleman).

Thanks for your responses!

**Comment by AdrianLxM** [comment]
@Hebes24, if you enable local broadcast in xDrip and disable that you get the values from Share, NightWatch will automatically show you the values.
No need to waste mobile data. :)

**Comment by Hebes24** [comment]
Wow, that's simple. Almost makes me feel silly for thinking uploading to Share was the only way to get this to work, haha.

I switched to that method and the deltas look correct. I'd still be willing to test out the fix for Share though if you still need assistance with that.

**Comment by AdrianLxM** [comment]
Thanks @Hebes24. I'll come back to you. Glad there was an easy solution for you.

**Comment by Hebes24** [comment]
Me too! And Thanks for developing these apps. It's really taken my CGM experience to a new level. I really appreciate it!

**Comment by ryanchen26** [comment]
I've been using the NW 2.0.3 apk download from the project site and I've been noticing the reversed (+/-) sign issue as well.  I get the data from the Dexcom share account and would be thrilled to test future releases if provided an APK.  Great App! I'm a big fan of the falling fast alarm. Very helpful.

**Comment by AdrianLxM** [comment]
Ha, sorry, I forgot. I'll put it on my todo list again. Thanks for reminding me.

**Comment by bw396704** [comment]
I am also having a reverse sign issue. I am using dexcom server for data.   I'm really not tech savvy,  so what can I do to fix?

**Comment by AdrianLxM** [comment]
@Hebes24 @bw396704 @ryanchen26
I've created an apk with a  fixed version. It would be great if you could test it and give a quick feedback:
http://bit.ly/1Pw0OmT

**Comment by bw396704** [comment]
Just did and appears to be working now.  Thank you so much!

**Comment by AdrianLxM** [comment]
I made this apk to the latest beta version. There were so many fixes and the adoption to Android Marshmallow already waiting to be release: [Download Page](https://github.com/StephenBlackWasAlreadyTaken/NightWatch/blob/master/Download.md)

**Comment by ryanchen26** [comment]
Looks great, well done!
![img_20160115_141242](https://cloud.githubusercontent.com/assets/16513711/12366893/f921bee6-bb92-11e5-80f9-ea1f263565db.jpg)
