### ISSUE TITLE
Nightwatch displaying xlxlx

### ISSUE THREAD

**Issue by samihusseingit** [StephenBlackWasAlreadyTaken/NightWatch#80]
Hello

I have xdrip sending data to azure night scout site.

Then another phone had nightwatch app with it pointing to site.  

Everything is good except at the top left of nightwatch below minutes it is showing

5 minutes
XlXlX.  

I think that this is supposed to show the values like +0.2mmol or  -0.5 something like that.

Any help is appreciated

I am using xdrip+

Regards
Susan

**Comment by AdrianLxM** [comment]
Did you enable "raw" in Nightscout?
I think for NightWatch to show the raw values, they need to be enabled.

**Comment by samihusseingit** [comment]
Hello again.

I am not using the night scout app.   

Using xdrip+ to send to night scout website directly.

Therefore I don't think I need a night scout app with xdrip.


I can't set raw on the website itself
  I don't know why the nightwatch app is displaying XlXlX below the last minutes.

**Comment by AdrianLxM** [comment]
If you can't see raw on the website itself, you will see x'es instead of 
the raw values in Nightwatch.

**Comment by samihusseingit** [comment]
Ok.  Thank you for clarifying this.



I thought it was a bug :)

Best Regards,

Susan


________________________________
