### ISSUE TITLE
Pulling and displaying OpenAPS Nightscout Data 

### ISSUE THREAD

**Issue by ryanchen26** [StephenBlackWasAlreadyTaken/NightWatch#98]
Since upgrading to android 7.0.1 I lost the ability to use the nightwatch watchfaces but back when it did work it would have been useful to have a few assignable number fields showing OpenAPS related data. Since there is an option to pull bg from nightscout, would it be reasonable to pull basal, iob, cob, status as well for display? Thanks.

**Comment by AdrianLxM** [comment]
Being released in the next couple of days, there will be a version of NSClient that will have the temp-basals in the chart of the watchfaces, avgDelta and IOB. (IOB calculated locally by the AndroidAPS plugin, should be very similar, if the parameters are the same as in OpenAPS).

Here is a preview: https://twitter.com/FrauLoop/status/887279941670326272

If you want an early APK, please contact me.

**Comment by ryanchen26** [comment]
Wonderful! If you need more testers I would be happy to try out the latest apk build and report back. Either way, good job!

**Comment by ryanchen26** [comment]
Any news regarding that new APK for nightwatch? Thanks!

**Comment by AdrianLxM** [comment]
@ryanchen26 it is not NightWatch but NSClient: app-nsclient-wear-release is a version of AndroidAPS without the loop stuff that downloads the things from NS to the phone. Also has the "Nightwatch" Android-Wear watchfaces included.
In contrast to NW, it will also plot the temp basals should you use another loop system that uploads to NS.

https://github.com/MilosKozak/AndroidAPS/releases

**Comment by badgerisop** [comment]
Can you log in to Dexcom share with NS client like you can with NW??

**Comment by AdrianLxM** [comment]
No. If you want to loop with AAPS off Share data, you can activate the Share2NS bridge in NightScout @bwclarke

**Comment by ryanchen26** [comment]
@AdrianLxM 
Nice. Works great. I should have read your previous message more carefully. I kept checking the NW page for updates.

**Comment by badgerisop** [comment]
No looping. Just looking for a watch face that doesn’t require a phone app but can be used to follow my sons Dexcom data.

I have the NS bridge set up already.
